Fix: Immutability of Int is broken by BigInt method (#332)
google/starlark-go pull request #333
Opened 2021-01-04 16:04 UTC by gfcapella

The interface of Int assumes the value is immutable but a reference to
its content is leaked through the BigInt() method, which is mutable.
This fix resolves the leak by:
- making a copy of the *big.Int in MakeBigInt()
- returning a copy of the *big.Int content in BigInt()
- creating an internal method bigInt() for internal use that still
returns reference to the internal big.Int

Fixes: #332

2021-01-14 05:06 UTC, alandonovan requested changes
Sorry for the delay. Logic looks good. Only very minor doc comment tweaks. Thanks for the PR!

2021-01-14 05:06 UTC, alandonovan commented on starlark/int.go
> +// The new Int value will contain a copy of x, the caller is safe to modify x.
Replace comma by semicolon or period.

2021-01-14 05:06 UTC, alandonovan commented on starlark/int.go
> +// BigInt returns a copy of the value as a big.Int.
// BigInt returns a new big.Int with the same value as the Int.

(and strike the second line

2021-01-14 05:06 UTC, alandonovan commented on starlark/int.go
> +// reference and any modification will change the state of i
Missing period.

2021-01-16 21:39 UTC, gfcapella commented
No problem! comments have now the fixes requested

2021-01-18 01:14 UTC, alandonovan approved these changes

2021-01-18 01:15 UTC, merged