starlark: fall back to slow Ints if mmap fails
google/starlark-go pull request #398
Opened 2022-02-16 16:50 UTC by adonovan

The Int optimization uses a 4GB virtual address allocation to represent
32-bit values as addressed to avoid allocation. However, some environments
have limited address space.

This change permits the mmap to fail, and in that case it prints a warning
and falls back to always allocating a big.Int, even for small numbers.
Each access to an Int must check the smallints global to see whether the
optimization is active.  The extra dynamic check doesn't cost much:

$ go test -run=nope -bench=BenchmarkStarlark -count=3 ./starlark    # > before, after
$ go install golang.org/x/perf/cmd/benchstat@latest
$ ~/go/bin/benchstat  before after
name                                  old time/op  new time/op   delta
Starlark/bench_bigint-16               206µs ± 0%    212µs ± 0%   ~     (p=0.100 n=3+3)
Starlark/bench_builtin_method-16       283µs ± 1%    294µs ± 9%   ~     (p=1.000 n=3+3)
Starlark/bench_calling-16              280µs ± 1%    290µs ± 1%   ~     (p=0.100 n=3+3)
Starlark/bench_gauss-16               9.30ms ± 5%   9.55ms ± 2%   ~     (p=0.700 n=3+3)
Starlark/bench_int-16                 53.7µs ± 1%   59.6µs ± 1%   ~     (p=0.100 n=3+3)
Starlark/bench_mix-16                 99.3µs ± 1%  106.6µs ±10%   ~     (p=0.100 n=3+3)
Starlark/bench_range_construction-16   238ns ± 1%    244ns ± 2%   ~     (p=0.100 n=3+3)
Starlark/bench_range_iteration-16     5.44µs ± 2%   5.67µs ± 1%   ~     (p=0.100 n=3+3)

Fixes #394

2022-02-24 22:22 UTC, adonovan commented
Ping @brandjon...

2022-06-27 17:15 UTC, aarzilli commented
Ping?

2022-08-15 21:06 UTC, tetromino approved these changes
Seems reasonable. Would be good to have a test, though (e.g. set RLIMIT_AS, see if int tests still pass).

2022-08-16 13:42 UTC, adonovan commented
> Seems reasonable. Would be good to have a test, though (e.g. set RLIMIT_AS, see if int tests still pass).

Done, though it's a pain because it requires fork+execing a child process, and it requires ulimit -v which is not available on MacOS or Windows.

2022-08-16 14:25 UTC, adonovan commented
@tetromino, PTAL at the changes to the build tags, go.mod/sum files, Actions workflow config, and of course the test.

2022-08-16 14:48 UTC, tetromino requested changes

2022-08-16 14:48 UTC, tetromino commented on starlark/int_test.go
> -func TestImmutabilityBigInt(t *testing.T) {
Was `TestImmutabilityBigInt` deleted by mistake?

2022-08-16 14:57 UTC, adonovan commented on starlark/int_test.go
> -func TestImmutabilityBigInt(t *testing.T) {
Yes! Good catch. Restored now.

2022-08-16 15:51 UTC, tetromino approved these changes
Looks good!

2022-08-16 15:51 UTC, merged